SELECT (CONCAT(NAME, '(',SUBSTRING(OCCUPATION, 1, 1),')'))
FROM OCCUPATIONS
ORDER BY NAME;

SELECT CONCAT_WS(" ", "There are a total of",COUNT(NAME),CONCAT( OCCUPATION, "s"))
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(NAME) ASC, OCCUPATION
