SELECT MIN( IF( OCCUPATION ="Doctor", NAME, NULL) )AS Doctor,  MIN( IF( OCCUPATION ="Professor", NAME, NULL) )AS Professor,  MIN( IF( OCCUPATION ="Singer", NAME, NULL) )AS Singer,  MIN( IF( OCCUPATION ="Actor", NAME, NULL) )AS Actor   
FROM (SELECT NAME, OCCUPATION, ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME ) AS ROW_NUM FROM OCCUPATIONS) AS ORD 
GROUP BY ROW_NUM;

-- SELECT * FROM OCCUPATIONS
