-- CREATE TABLE EMPLOYEES(
--     ID INT,
--     NAME VARCHAR(64),
--     SALARY INT
-- );

SELECT * FROM EMPLOYEES;

-- INSERT INTO EMPLOYEES VALUES
--     (1, 'KRIS', 1420),
--     (2, 'ASHLEY', 2006),
--     (3, 'JULIA', 2210),
--     (4, 'MARIA', 3000);

SELECT ROUND(SUM(SALARY - CAST(REPLACE(CAST(SALARY AS CHAR(6)),'0','') AS UNSIGNED))/COUNT(ID))
FROM EMPLOYEES;
